// Builds romfs/main.js for the Switch (nx.js) from the web version of the game.
// The web page (../index.html) is the single source of truth: its game script
// already detects the nx.js runtime and switches canvas, fonts, input and save
// data to the Switch APIs.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]);
if (!scripts.length) throw new Error('No inline <script> found in ../index.html');
const game = scripts[scripts.length - 1];

mkdirSync(new URL('./romfs/', import.meta.url), { recursive: true });
writeFileSync(new URL('./romfs/main.js', import.meta.url), `// Generated by build.mjs from ../index.html - do not edit by hand.\n${game}`);
console.log(`romfs/main.js written (${(game.length / 1024).toFixed(1)} KB)`);
